export const productz = [
  {
    id: 1,
    name: "1k Resistor",
    url: "/products/1k-resistor.jpg",
    rating: 5,
    price: 50,
    cat: "resistor",
    sub: "fixed resistors",
  },
  {
    id: 2,
    name: "10k Resistor",
    url: "/products/10k-resistor.jpg",
    rating: 4,
    price: 50,
    cat: "resistor",
    sub: "variable resistors",
  },
  {
    id: 3,
    name: "IN4007 Diode",
    url: "/products/4007-diode.jpg",
    rating: 5,
    price: 100,
    cat: "diodes",
    sub: "rectifying diodes",
  },
  {
    id: 4,
    name: "L7812",
    url: "/products/L7812.jpg",
    rating: 2,
    price: 200,
    cat: "semiConductors",
    sub: "voltage regulators",
  },
  {
    id: 5,
    name: "NE555 Timer IC",
    url: "/products/NE555.jpg",
    rating: 5,
    price: 50,
    cat: "ICs",
    sub: "timers",
  },
  {
    id: 6,
    name: "Soldering Iron",
    url: "/products/soldering iron.jpg",
    rating: 5,
    price: 50,
    cat: "accessories",
    sub: "soldering tools",
  },
];
